[package]
name = "arcshift"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
rand="0.8"

[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = ["checkpoint"] }

[dev-dependencies]
