exclude_re = [
    #"replace \\* with \\+ in ArcShift<T>::early_drop_opt",
    ".*replace is_superseded_by_tentative -> bool with false.*", #Because it still works, it just goes a little slower with this change
]
