name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable
    - name: Run tests
      run: cargo +stable clippy --features=validate,debug --workspace
