name: Loom

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install stable
      - name: Install nextest
        run: cargo install cargo-nextest
      - name: Loom
        run: cd arcshift && ./run_loom_fast.sh
