name: Miri

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: Miri
        run: rustup component add --toolchain nightly miri && cd arcshift && cargo +nightly miri test --features=disable_slow_tests
      - name: Miri (nightly-only-feature)
        run: rustup component add --toolchain nightly miri && cd arcshift && cargo +nightly miri test --features=disable_slow_tests,nightly
