name: Mutants

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: rustup toolchain install stable
      - name: Install cargo mutants
        run: cargo install cargo-mutants
      - name: Mutants
        run: cd arcshift && ./run_mutants.sh
