name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "37 7 * * 1,5"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable
    - name: Run tests
      run: cargo +stable test --features=validate --workspace
    - name: Run tests (release)
      run: cargo +stable test --release --workspace
    - name: Run tests (release)
      run: cargo +stable test --release --features=validate --workspace
    - name: Test (no default features)
      run: cargo +stable test --no-default-features
    - name: Build (all features)
      run: cargo +stable build --all-features
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Run tests (release, nightly-only-features)
      run: cargo +nightly test --release --features=validate,nightly --workspace
    - name: Cargo doc
      run: cargo +stable doc --workspace


