name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly
      run: rustup toolchain install nightly && rustup toolchain install stable
    - name: Run tests (stable)
      run: cargo +stable test --release --workspace
    - name: Run tests (stable)
      run: cargo +stable test --release --features=validate --workspace
    - name: Shuttle (stable)
      run: cargo +stable test --lib --tests -p arcshift --features=validate,shuttle --release
    - name: Miri (nightly)
      run: rustup component add --toolchain nightly miri && cd arcshift && cargo +nightly miri test --features=disable_slow_tests
    - name: Loom
      run: LOOM_MAX_PREEMPTIONS=1 RUSTFLAGS="--cfg loom" cargo test --lib --tests --features=disable_slow_tests --release
